module.exports = {
  Animal: {
    "AARDVARK": "AARDVARK",
    "BABOON": "BABOON",
    "CAMEL": "CAMEL",
    "DEER": "DEER",
    "ELEPHANT": "ELEPHANT",
    "FROG": "FROG",
    "GORILLA": "GORILLA",
    "HARE": "HARE",
    "IMPALA": "IMPALA",
    "JAGUAR": "JAGUAR",
    "KANGAROO": "KANGAROO",
    "LION": "LION",
    "MOOSE": "MOOSE",
    "NEWT": "NEWT",
    "OCTOPUS": "OCTOPUS",
    "PENGUIN": "PENGUIN",
    "QUETZAL": "QUETZAL",
    "RABBIT": "RABBIT",
    "SALMON": "SALMON",
    "TORTOISE": "TORTOISE",
    "UAKARIS": "UAKARIS",
    "VAQUITA": "VAQUITA",
    "WHALE": "WHALE",
    "X_RAY_TETRA": "X_RAY_TETRA",
    "YAK": "YAK",
    "ZEBRA": "ZEBRA"
  }
};