import unittest


from animal_deck import AnimalDeck


class AnimalDeckTest(unittest.TestCase):

    def test_get_deck_in_order_return_52_cards_correctly_formatted(self):
        animal_deck = AnimalDeck()
        self.assertListEqual(animal_deck.cards, [
            "AARDVARK",
            "AARDVARK",
            "BABOON",
            "BABOON",
            "CAMEL",
            "CAMEL",
            "DEER",
            "DEER",
            "ELEPHANT",
            "ELEPHANT",
            "FROG",
            "FROG",
            "GORILLA",
            "GORILLA",
            "HARE",
            "HARE",
            "IMPALA",
            "IMPALA",
            "JAGUAR",
            "JAGUAR",
            "KANGAROO",
            "KANGAROO",
            "LION",
            "LION",
            "MOOSE",
            "MOOSE",
            "NEWT",
            "NEWT",
            "OCTOPUS",
            "OCTOPUS",
            "PENGUIN",
            "PENGUIN",
            "QUETZAL",
            "QUETZAL",
            "RABBIT",
            "RABBIT",
            "SALMON",
            "SALMON",
            "TORTOISE",
            "TORTOISE",
            "UAKARIS",
            "UAKARIS",
            "VAQUITA",
            "VAQUITA",
            "WHALE",
            "WHALE",
            "X_RAY_TETRA",
            "X_RAY_TETRA",
            "YAK",
            "YAK",
            "ZEBRA",
            "ZEBRA"
        ])

    def test_shuffle_returns_all_cards_in_any_order(self):
        deck = AnimalDeck()
        deck.shuffle()
        self.assertListEqual(sorted(deck.shuffle()), [
            "AARDVARK",
            "AARDVARK",
            "BABOON",
            "BABOON",
            "CAMEL",
            "CAMEL",
            "DEER",
            "DEER",
            "ELEPHANT",
            "ELEPHANT",
            "FROG",
            "FROG",
            "GORILLA",
            "GORILLA",
            "HARE",
            "HARE",
            "IMPALA",
            "IMPALA",
            "JAGUAR",
            "JAGUAR",
            "KANGAROO",
            "KANGAROO",
            "LION",
            "LION",
            "MOOSE",
            "MOOSE",
            "NEWT",
            "NEWT",
            "OCTOPUS",
            "OCTOPUS",
            "PENGUIN",
            "PENGUIN",
            "QUETZAL",
            "QUETZAL",
            "RABBIT",
            "RABBIT",
            "SALMON",
            "SALMON",
            "TORTOISE",
            "TORTOISE",
            "UAKARIS",
            "UAKARIS",
            "VAQUITA",
            "VAQUITA",
            "WHALE",
            "WHALE",
            "X_RAY_TETRA",
            "X_RAY_TETRA",
            "YAK",
            "YAK",
            "ZEBRA",
            "ZEBRA"])


if __name__ == "__main__":
    unittest.main()
