using FluentAssertions;

namespace McrDigital.Bootcamp1.Cards.Tests
{
    using Xunit;

    public class MixedDeckTest
    {
        [Fact]
        public void ShouldGetDeckInOrderAndReturn52CardsCorrectlyFormatted()
        {
            var deck = new MixedDeck();
            var expectedCards = new string[]
            {
                "Aardvark",
                "ace of clubs",
                "Aardvark",
                "2 of clubs",
                "Baboon",
                "3 of clubs",
                "Baboon",
                "4 of clubs",
                "Camel",
                "5 of clubs",
                "Camel",
                "6 of clubs",
                "Deer",
                "7 of clubs",
                "Deer",
                "8 of clubs",
                "Elephant",
                "9 of clubs",
                "Elephant",
                "10 of clubs",
                "Frog",
                "jack of clubs",
                "Frog",
                "queen of clubs",
                "Gorilla",
                "king of clubs",
                "Gorilla",
                "ace of diamonds",
                "Hare",
                "2 of diamonds",
                "Hare",
                "3 of diamonds",
                "Impala",
                "4 of diamonds",
                "Impala",
                "5 of diamonds",
                "Jaguar",
                "6 of diamonds",
                "Jaguar",
                "7 of diamonds",
                "Kangaroo",
                "8 of diamonds",
                "Kangaroo",
                "9 of diamonds",
                "Lion",
                "10 of diamonds",
                "Lion",
                "jack of diamonds",
                "Moose",
                "queen of diamonds",
                "Moose",
                "king of diamonds",
                "Newt",
                "ace of hearts",
                "Newt",
                "2 of hearts",
                "Octopus",
                "3 of hearts",
                "Octopus",
                "4 of hearts",
                "Penguin",
                "5 of hearts",
                "Penguin",
                "6 of hearts",
                "Quetzal",
                "7 of hearts",
                "Quetzal",
                "8 of hearts",
                "Rabbit",
                "9 of hearts",
                "Rabbit",
                "10 of hearts",
                "Salmon",
                "jack of hearts",
                "Salmon",
                "queen of hearts",
                "Tortoise",
                "king of hearts",
                "Tortoise",
                "ace of spades",
                "Uakaris",
                "2 of spades",
                "Uakaris",
                "3 of spades",
                "Vaquita",
                "4 of spades",
                "Vaquita",
                "5 of spades",
                "Whale",
                "6 of spades",
                "Whale",
                "7 of spades",
                "XRayTetra",
                "8 of spades",
                "XRayTetra",
                "9 of spades",
                "Yak",
                "10 of spades",
                "Yak",
                "jack of spades",
                "Zebra",
                "queen of spades",
                "Zebra",
                "king of spades"
            };
            var actualCards = deck.GetCards();
            actualCards.Should().BeEquivalentTo(expectedCards, options => options.WithStrictOrdering());
        }

        [Fact]
        public void ShouldShuffleAndReturnCardsInAnyOrder()
        {
            var deck = new MixedDeck();
            deck.Shuffle();
            var fullMixedDeck = new string[]
            {
                "Aardvark",
                "ace of clubs",
                "Aardvark",
                "2 of clubs",
                "Baboon",
                "3 of clubs",
                "Baboon",
                "4 of clubs",
                "Camel",
                "5 of clubs",
                "Camel",
                "6 of clubs",
                "Deer",
                "7 of clubs",
                "Deer",
                "8 of clubs",
                "Elephant",
                "9 of clubs",
                "Elephant",
                "10 of clubs",
                "Frog",
                "jack of clubs",
                "Frog",
                "queen of clubs",
                "Gorilla",
                "king of clubs",
                "Gorilla",
                "ace of diamonds",
                "Hare",
                "2 of diamonds",
                "Hare",
                "3 of diamonds",
                "Impala",
                "4 of diamonds",
                "Impala",
                "5 of diamonds",
                "Jaguar",
                "6 of diamonds",
                "Jaguar",
                "7 of diamonds",
                "Kangaroo",
                "8 of diamonds",
                "Kangaroo",
                "9 of diamonds",
                "Lion",
                "10 of diamonds",
                "Lion",
                "jack of diamonds",
                "Moose",
                "queen of diamonds",
                "Moose",
                "king of diamonds",
                "Newt",
                "ace of hearts",
                "Newt",
                "2 of hearts",
                "Octopus",
                "3 of hearts",
                "Octopus",
                "4 of hearts",
                "Penguin",
                "5 of hearts",
                "Penguin",
                "6 of hearts",
                "Quetzal",
                "7 of hearts",
                "Quetzal",
                "8 of hearts",
                "Rabbit",
                "9 of hearts",
                "Rabbit",
                "10 of hearts",
                "Salmon",
                "jack of hearts",
                "Salmon",
                "queen of hearts",
                "Tortoise",
                "king of hearts",
                "Tortoise",
                "ace of spades",
                "Uakaris",
                "2 of spades",
                "Uakaris",
                "3 of spades",
                "Vaquita",
                "4 of spades",
                "Vaquita",
                "5 of spades",
                "Whale",
                "6 of spades",
                "Whale",
                "7 of spades",
                "XRayTetra",
                "8 of spades",
                "XRayTetra",
                "9 of spades",
                "Yak",
                "10 of spades",
                "Yak",
                "jack of spades",
                "Zebra",
                "queen of spades",
                "Zebra",
                "king of spades"
            };
            var actualCards = deck.GetCards();
            actualCards.Should().BeEquivalentTo(fullMixedDeck).And.NotContainInOrder(fullMixedDeck);
        }
    }
}